# Base Image
FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Build Image
FROM base AS builder
WORKDIR /app
COPY . .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm build:nestjs-common
RUN pnpm build:auth-service
RUN pnpm --filter auth-service deploy --prod /prod/auth-service

# Runtime Image
FROM base AS runtime
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nestjs

COPY --from=builder /prod/auth-service ./
COPY --from=builder /app/apps/auth-service/dist ./dist

RUN chown -R nestjs:nodejs /app
USER nestjs

EXPOSE 3300
CMD ["node", "dist/main"]
